# Generated by Django 5.1.6 on 2025-06-03 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_name', models.CharField(max_length=100)),
                ('std_roll', models.IntegerField(primary_key=True, serialize=False)),
                ('std_email', models.EmailField(max_length=254)),
                ('std_joining_date', models.DateTimeField(default=datetime.datetime.now)),
                ('std_course', models.ManyToManyField(to='courses.courses')),
            ],
        ),
    ]
