# Generated by Django 5.2.1 on 2025-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_roll',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
