# Generated by Django 5.1.6 on 2025-06-05 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_std_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_password',
            field=models.CharField(default='demo123', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
