# Generated by Django 5.1.6 on 2025-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_title', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('DS', 'Data Science')], max_length=100)),
                ('course_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
