# Generated by Django 5.1.6 on 2025-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_title',
            field=models.CharField(max_length=100),
        ),
    ]
