# Generated by Django 5.2.1 on 2025-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
