# Generated by Django 5.1.6 on 2025-06-20 05:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=100)),
                ('noitce_message', models.TextField(default='')),
                ('notice_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
