# Generated by Django 5.1.6 on 2025-06-20 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('library', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_confirm_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('STD', 'STUDENT'), ('TCH', 'TEACHER'), ('LIB', 'LIBRARIAN'), ('FM', 'FEEMANAGER'), ('DN', 'DEAN')], max_length=100)),
                ('fee_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_confirm_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('STD', 'STUDENT'), ('TCH', 'TEACHER'), ('LIB', 'LIBRARIAN'), ('FM', 'FEEMANAGER'), ('DN', 'DEAN')], max_length=100)),
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_confirm_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('STD', 'STUDENT'), ('TCH', 'TEACHER'), ('LIB', 'LIBRARIAN'), ('FM', 'FEEMANAGER'), ('DN', 'DEAN')], max_length=100)),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_books', to='library.book')),
                ('course', models.ManyToManyField(related_name='student_courses', to='courses.course')),
                ('payment', models.ManyToManyField(related_name='student_fee_transactions', to='payment.transaction')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_confirm_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('STD', 'STUDENT'), ('TCH', 'TEACHER'), ('LIB', 'LIBRARIAN'), ('FM', 'FEEMANAGER'), ('DN', 'DEAN')], max_length=100)),
                ('course', models.ManyToManyField(related_name='teacher_courses', to='courses.course')),
                ('students', models.ManyToManyField(related_name='teacher_teaching_students', to='users.studentprofile')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
