# Generated by Django 5.1.6 on 2025-06-20 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electrical'), ('IT', 'Information Technology'), ('ME', 'Mechanical'), ('AI/ML', 'Artifical Intelligence and Machine Learning'), ('DS', 'Data Science')], max_length=100)),
                ('course_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_intake', models.IntegerField()),
            ],
        ),
    ]
